version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sql-mode=STRICT_ALL_TABLES,NO_UNSIGNED_SUBTRACTION
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --log-bin-trust-function-creators=1
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db:/opt/db/
      - ./db/docker-entrypoint.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - DB_HOST=mysqldb
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
    volumes:
      - ${UPLOAD_FOLDER}:/app/data
    stdin_open: true
    tty: true

volumes:
  db:
  upload_dir: